server:
  port: 8889

eureka:
  instance:
    hostname: localhost
  client:
    #通过下面两个值 确定为server
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/