server:
    port: 8888
spring:
    application:
        name: hnister-config-server
    cloud:
        config:
            server:
                git:
                    uri: file:///Users/zhaoyuening/Documents/project/hnister-parent/
                    search-paths: hnister-config-server/config-repo

eureka:
    client:
        serviceUrl:
            defaultZone: http://eureka.hnister.cn:8889/eureka/